---
title: "News Archive"
toc: false
---

* **May 2025**
I presented my work at the [SIAM Dynamical Systems Conference](https://www.siam.org/conferences-events/siam-conferences/ds25/) in Denver.

* **April 2025**
I attended the [Rising Stars in Computational and Data Sciences](https://risingstars.oden.utexas.edu/) workshop at the Oden Institute in UT Austin.

* **January 2025**
I presented a poster at [Dynamics Days 2025](https://www.ddays.org/2025/) in Denver.

* **November 2024**
I visited Dick McGehee's group at the University of Minnesota and presented my work on misperception of public support for climate policy, as well as my work on models of exoplanetary atmospheres.

* **July 2024**
At [IC2S2](https://ic2s2-2024.org/topics) in Philadelphia I presented my work on modeling misperception of public support for climate policy.

* **June 2024**
I presented my work on misperception of public support of climate policy at [NetSci](https://netsci2024.com) in Quebec City. I was awarded Honorable Mention for Best Oral Presentation by an Early-Career Researcher.
I presented my work at the SIAM Conference on Mathematics of Planet Earth [MPE24](https://www.siam.org/conferences/cm/conference/mpe24) in Portland.

* **May 2024** I spent a week at Collaborate @ ICERM working on a project titled Modeling and Analysis of Candidate Momentum in U.S. Primary Elections Using Campaign Contributions with Izabel Aguiar, Samantha Linn, Alexandria Volkening, and Sam Zhang.

* **March 2024** I was awarded the [SIAM Science Policy Fellowship](https://sinews.siam.org/Details-Page/2024-siam-science-policy-fellows)
